name: Generate TVL Snapshot

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  discover-adapters:
    runs-on: ubuntu-latest
    outputs:
      adapter_paths: ${{ steps.find-adapters.outputs.paths }}
    
    steps:
    - uses: actions/checkout@v4

    - id: find-adapters
      run: |
        if ! ADAPTERS=$(ls -d adapters/*/ | jq -R -s -c 'split("\n")[:-1]'); then
          echo "Error: Failed to find adapters"
          exit 1
        fi
        echo "paths=$ADAPTERS" >> $GITHUB_OUTPUT

  generate-snapshot:
    needs: discover-adapters
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        adapter: ${{ fromJson(needs.discover-adapters.outputs.adapter_paths) }}
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
  
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE }}
        aws-region: eu-north-1

    - name: Install adapter dependencies
      run: |
        cd ${{ matrix.adapter }}
        npm install

    - name: Generate snapshot output
      timeout-minutes: 15
      run: |
        cd ${{ matrix.adapter }}
        if ! npm run compile; then
          echo "Error: Failed to compile ${{ matrix.adapter }}"
          exit 1
        fi
        if ! npm run start; then
          echo "Error: Failed to generate snapshot for ${{ matrix.adapter }}"
          exit 1
        fi
    
    - name: Sync files to S3 bucket
      run: |
        cd ${{ matrix.adapter }}
        aws s3 sync out s3://${{ secrets.AWS_S3_BUCKET_NAME }}
